// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQA28xvbU4vFMT2sVq2RHCDhrI2gAf-rA',
    appId: '1:898812820164:web:88eacbf1532caad5b86791',
    messagingSenderId: '898812820164',
    projectId: 'studenthub-16657',
    authDomain: 'studenthub-16657.firebaseapp.com',
    storageBucket: 'studenthub-16657.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADAT_-H_8AMHtWlqkIUpeZrAIRyvDJC7E',
    appId: '1:898812820164:android:721db0c07b9394b4b86791',
    messagingSenderId: '898812820164',
    projectId: 'studenthub-16657',
    storageBucket: 'studenthub-16657.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfL4jr4odVTwOZUNUkgz-ZK-gOm5kVUJw',
    appId: '1:898812820164:ios:d012022980d12939b86791',
    messagingSenderId: '898812820164',
    projectId: 'studenthub-16657',
    storageBucket: 'studenthub-16657.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );
}
